- name: Deploy Docker Container for Calculator
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker image
      community.docker.docker_image:
        name: aishjp/calculator:latest
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: Calculator
        image: aishjp/calculator:latest
        state: started
        restart_policy: always
